### ISSUE TITLE
Need APERTIF layout, specs and representative APERTIF primary beam

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/rodrigues#1]
@gigjozsa. APERTIF is 12 out of 14 dishes -- which 12? Need to make an APERTIF antenna table.

What is the APERTIF SEFD?

Also need a representative primary beam (not necessarily accurate). Maybe @foxmouldy can assist too.

**Comment by gijzelaerr** [comment]
@gigjozsa whagt is the status of this?

**Comment by gijzelaerr** [comment]
nobody seems to care, closing this issue.
