### ISSUE TITLE
Merge ceiling-kat into RODRIGUES

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/rodrigues#16]
RODRIGUES and ceiling-kat have been running for a while now, and I think at this stage it is good to step back and look what we really want and decide where the project will from here. To reduce complexity and duplication I  want to merge ceiling-kat into RODRIGUES to make a more universal configurable contained simulation scheduler and result visualiser. But we need to be careful this doesn’t get out of scope and burns all my time while i’m here.

**Comment by gijzelaerr** [comment]
this has mostly been done, the ceiling-kat form only needs to be merged

**Comment by gijzelaerr** [comment]
the ceiling-kat form has been merged, not sure what container to use. @SpheMakh ?

**Comment by SpheMakh** [comment]
This has been fixed
