### ISSUE TITLE
Missing libfreetype / libpng packages while issuing "pip3 install -r requirements.txt"

### ISSUE THREAD

**Issue by JulienNGirard** [ska-sa/rodrigues#57]
On a fresh installed ubuntu 14.04 LTS, after following the install instructions, 
The following "pip3 install -r requirements.txt" issue a missing packages error during the installation of matplotlib from pip3.

tail of error:
> * The following required packages can not be built:
> 
>                         * freetype, png
> 
> ----------------------------------------
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_user/matplotlib
> Storing debug log for failure in /home/user/.pip/pip.log

Problem is solved by installing but documentation must be updated to include the apt-install of: 
libfreetype6-dev libpng12-dev

**Comment by gijzelaerr** [comment]
fixed https://github.com/ska-sa/rodrigues/commit/4df69fc6fd0cdf5d91a8754345a5e0cb1c51b54a
