### ISSUE TITLE
RODRIGUES in production mode generates Bad Request when not in debug mode

### ISSUE THREAD

**Issue by JulienNGirard** [ska-sa/rodrigues#59]
run command:
SERVER_NAME=localhost SECRET_KEY=fzeioruzeio DEBUG=true docker-compose start

then, in the web browser, a Bad Request (400) error is issued.
Webserver shows the Scheduler only in debug mode, but the "DEBUG=true" before "docker-compose" does not activate the debug mode for some reason.

Temporary solution: alter manually rodrigues/settings/container.py
to enforce  "DEBUG=True" after the existing DEBUG line.

then restart the server and it works.

**Comment by gijzelaerr** [comment]
ok, it looks like the `start` command actually ignores the environment variables. please use `up` and `up -d` if you want to fork it to the background.

I think we should just completely ignore the `start` command, it is not really documented also https://docs.docker.com/compose/reference/start/
