### ISSUE TITLE
Need to restart everything after the server is rebooted

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/rodrigues#6]
I understand fig has to be restarted manually for now -- Gijs can you please add instructions here? At some point we need to add this to the startup scripts.

**Comment by gijzelaerr** [comment]
this is now quite easy to do https://docs.docker.com/engine/admin/host_integration/

**Comment by gijzelaerr** [comment]
this is now done with a cronjob (crontab -e):

```
@reboot cd ~/rodrigues && ./start.sh
```

Where start is a shellscript:
```
SECRET_KEY=topsecret
SERVER_NAME=localhost
docker-compose up -d
```
