### ISSUE TITLE
Container to see multiple input files from directory ? Input/output communication

### ISSUE THREAD

**Issue by JulienNGirard** [ska-sa/rodrigues#65]
I have the issue that when I try to batch process a series of fits files from a folder, only one file is available in the container under /input. However, I want to be able to apply the effect of one container to a series of images (let's say 10 different fits file that will undergo a division by 100 and then save the result as a dits file).
I tried to circumvent this by getting the absolute directory path from the filename but it does not work because only the selected file is mounted in the container.

This is leading me to some questions:

1) for fits files: 
If I want to upload a bunch of fits files from a directory (from local or from overseas), it is more convenient to add the path to the folder directly. Do you think it is a reasonable solution (there is still the possibility to upload a single tar file containing multiple files, and mount the tar in the container but still.

2) for MS: users like me, for development, are using rodrigues locally will then be able to select local .MS files
(I comes without saying that users overseas should not upload directly MS files, but rather a tar MS file to keep file integrity...)

3) General question about Rodrigues, is there a general "input" directory, or a "repository" in which a bunch of files can be put in ?  I know that the "storage" directory stores input/ output/ and json files for each task but how to place a bunch of reference files in a space that will be seen by the whole system? 
Can I use storage to store a set of reference fits files (e.g. a series of 10 reference fits files).

4) I know that django enable the support of "FilePathField" which help the user to select a directory. Could it be a good enhancement to kliko or maybe completely useless?

Sorry if I am not clear.

**Comment by gijzelaerr** [comment]
Hi Julian,

1> I think for this you should fire a container per fits file. We could potentially make this easier within rodrigues.

2> I think a person should tar a MS set. It is technically hard to have the option to process/upload MS sets.

3> Basically that is this issue:https://github.com/ska-sa/rodrigues/issues/50. Which is unimplemented (yet(.

**Comment by gijzelaerr** [comment]
I'm closing this issue since I think your questions have been answered. Please reopen if you want to continue the discussion.
