### ISSUE TITLE
Dateutil error when initializing the DB after fresh install of rodrigues

### ISSUE THREAD

**Issue by JulienNGirard** [ska-sa/rodrigues#68]
OS: Fresh Ubuntu 14.04.4 LTS
Followed instructions:
```
sudo apt-get update
sudo apt-get install -y python-pip git
sudo pip install docker-compose
git clone https://github.com/ska-sa/rodrigues && cd rodrigues
```
and then
`user@user-rodrigues:~/rodrigues3/rodrigues$ docker-compose run worker python3 manage.py migrate`

> /code/rodrigues/settings/container.py:59: UserWarning: !!! SERVER_NAME is not set, using rodrigues.meqtrees.net !!!
>   warnings.warn('!!! SERVER_NAME is not set, using rodrigues.meqtrees.net !!!')
> ******* RODRIGUES SETTINGS *******
> DEBUG:	False
> SERVER_NAME:	rodrigues.meqtrees.net
> ALLOWED_HOSTS:	['rodrigues.meqtrees.net']
> SECRET_KEY:	"doesn't matter"
> SERVER_EMAIL:	False
> EMAIL_HOST:	smtp.mailgun.org
> EMAIL_HOST_USER:	False
> EMAIL_HOST_PASSWORD:	False
> HOST_STORAGE:	/home/user/rodrigues3/rodrigues/storage
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 345, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 348, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 398, in execute
>     self.check()
>   File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 426, in check
>     include_deployment_checks=include_deployment_checks,
>   File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 75, in run_checks
>     new_errors = check(app_configs=app_configs)
>   File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
>     return check_resolver(resolver)
>   File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
>     for pattern in resolver.url_patterns:
>   File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 33, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/usr/local/lib/python3.4/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
>     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
>   File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 33, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/usr/local/lib/python3.4/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
>     return import_module(self.urlconf_name)
>   File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1129, in _exec
>   File "<frozen importlib._bootstrap>", line 1471, in exec_module
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
>   File "/code/rodrigues/urls.py", line 14, in <module>
>     url(r'^scheduler/', include('scheduler.urls')),
>   File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 52, in include
>     urlconf_module = import_module(urlconf_module)
>   File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1129, in _exec
>   File "<frozen importlib._bootstrap>", line 1471, in exec_module
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
>   File "/code/scheduler/urls.py", line 2, in <module>
>     from scheduler import views
>   File "/code/scheduler/views.py", line 8, in <module>
>     from kliko.django_form import generate_form
>   File "/usr/local/lib/python3.4/dist-packages/kliko/__init__.py", line 5, in <module>
>     __version__ = pkg_resources.require("kliko")[0].version
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
>     raise VersionConflict(dist,req) # XXX put more info here
**> pkg_resources.VersionConflict: (python-dateutil 2.0 (/usr/lib/python3/dist-packages), Requirement.parse('python-dateutil==2.4.2'))**

try to install/uninstall with pip, pip3, python-dateutil or python-dateutil==2.4.2 and I always get this message.

thanks

**Comment by gijzelaerr** [comment]
This is caused by pykwalify being to strict on version number requirements. https://github.com/Grokzen/pykwalify/issues/55 Will try to find a workaround.

**Comment by gijzelaerr** [comment]
fixed per https://github.com/ska-sa/rodrigues/commit/e336e355f1cbdf5ff4a78f9419119b8f18f95c35, forced versions to match pykwalify requirements. Should work for now.
