### ISSUE TITLE
weight_fov parameter passed incorrectly

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/rodrigues#8]
Check out the failed sim here: http://ceiling-kat.meqtrees.net/simqueue/detail/3/

Looks like it's calling lwimager with weight_fov=120.0. Should have been a quantity string, i.e. "120arcsec". While you're at it, the FoV is better off specified in minutes. Also, rename it to "FoV override for uniform/robust weighting", leave the default setting blank, and not pass the parameter at all if blank (imager default is to use entire image as the weight FOV, which is the conventional thing to do).

**Comment by SpheMakh** [comment]
This has been fixed
