### ISSUE TITLE
Add button to re-create simulation based on previous simulation

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/rodrigues#9]
We have a "Reschedule" button which repeats a sim. A common use case is to repeat while making a minor change to the settings. What would be very nice is a button associated with a simulation result which takes us back to the "Create" screen and populates all fields with the settings used by that particular sim. @SpheMakh or @gijzelaerr ?

**Comment by gijzelaerr** [comment]
this is a bit hard now, since we don't store the form in the database anymore.

**Comment by gijzelaerr** [comment]
This is just not possble anymore, since we don't store the unrendered form. You can reschedule an existing simulation.
